{% set name = "jsonpath-ng" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 54252968134b5e549ea5b872f1df1168bd7defe1a52fed5a358c194e1943ddc3

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  entry_points:
    - jsonpath_ng=jsonpath_ng.bin.jsonpath:entry_point

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=18.5
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - jsonpath_ng
  requires:
    - pip
    - pytest
    - hypothesis
  commands:
    - pip check
    - jsonpath_ng --help
    - pytest tests -vv

about:
  home: https://github.com/h2non/jsonpath-ng
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python JSONPath Next-Generation
  description: |
    A final implementation of JSONPath for Python that aims to be standard compliant,
    including arithmetic and binary comparison operators.
  dev_url: https://github.com/h2non/jsonpath-ng
  doc_url: https://github.com/h2non/jsonpath-ng

extra:
  recipe-maintainers:
    - shcheklein
    - efiop
