{% set name = "jsonpath-ng" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f6f5f7fd4e5ff79c785f1573b394043b39849fb2bb47bcead935d12b00beab3c

build:
  skip: true #[py<37]
  number: 0
  entry_points:
    - jsonpath.py=jsonpath_ng.bin.jsonpath:entry_point
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools >=18.5
  run:
    - python
    - ply

test:
  source_files:
    - jsonpath_ng
    - tests
  imports:
    - jsonpath_ng
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -vv


about:
  home: https://github.com/h2non/jsonpath-ng
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Python JSONPath Next-Generation
  description: |
    A final implementation of JSONPath for Python that aims to be standard compliant,
    including arithmetic and binary comparison operators.
  dev_url: https://github.com/h2non/jsonpath-ng
  doc_url: https://github.com/h2non/jsonpath-ng
extra:
  recipe-maintainers:
    - shcheklein
    - efiop
