travis:
  secure:
    BINSTAR_TOKEN: w5UJP/KbdjX0rPHWl3DZDXC+lolmVmJhc+LDccgMwyRXEO2Y35hw/5ElqURCisSjFD5RBmPPBZ62XD3sTIOEk/6nZiunwEGNuhqvamWKrr08fCWKn5lCeh8VvYsoWpTxtg/mzyosVS4TkOPJKdEKbLJWhO0wlmd+CPqdgC8qV1aO9lzG5Nxfc4zbHxAKNm9URXszgxMh/HyOTTzAnQ+co73mi/afRIOFrIrfjqjHl0P7aMDqkUd4IGKf+gxR7L+plUUeWoQpAmC3H1AgptH0LA0M8+XMGpz7PfjusBmqBvxP8t2lNWMihcw6hjRBF4GVqjUuku9y6uJqYnwPjuVlLElT6v/BfTeUjrq0UuOmvqbHn86R3/sWIdAxVoi/zGV4+HnmPRLt4PfckYWbALru7m8QhqNxfmXfKfIVP8Ed2CZKcdziF9wCw9XneAepbJ27k+RI6csqoJF4bRYstcTLwDNqwKKKsiExELhtX6tdmQjIQptsgMTBxMfX3k3h+JlU2LHoU3mEIiJ4BqDe25DFckXl8zP+Ar+N1qDcXKFZBBJtRZz9FObz1awxU46brgO2ZAJPcHl/ue2dp1+7iWcfWIcjaKZGFrhh+OdXoi/YLbVo2Qoj64kfooq21v0UOsqoOQK3SDqFMdvUl54GHrjGo10hBsS0/sG3wnMmHqoH5Fw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
